performance:
  # Frame buffering
  buffer_size: 30
  queue_size: 10
  
  # Memory management
  memory_threshold: 80  # Trigger GC at 80% memory usage
  
  # GPU acceleration
  use_gpu: true
  batch_size: 4
  
  # CPU optimization
  cpu_threads: 4
  
  # Monitoring
  enable_monitoring: true
  metrics_interval: 1  # seconds